name: 05 Basics Events Schedule

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print-hello-world
        run: echo "hello world"
