name: 07 Basics ECondition

on:
  pull_request:
    types:
      - closed
jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: print-hello-worlds
        run: echo "hello world"
