name: 12 Basics Permission_Token
run-name: ${{ github.actor }} Explaining Varaibles with Practical Example Run_Number ${{ github.run_number }}

# env:
  # NAME: value

on: workflow_dispatch
# permissions:
#   issues: write

jobs:
  open-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Simulate testing failure
        run: exit 1
      - name: Open New Issue
        if: failure()
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          ${{ vars.CREATE_ISSUE_API_ENDPOINT }} \
          -d '{"title":"Testing Failure","body":"This Issue opened by Github Action"}'
