name: 18 Basic services alternative
run-name: ${{ github.actor }} Explaining Varaibles with Practical Example Run_Number ${{ github.run_number }}

on: workflow_dispatch

jobs:
  Redis-Job:
    runs-on: ubuntu-latest
    services:
      redis: 
        image:  redis:latest
    
  
    steps:
      - name: Install Redis redis-cli
        run: sudo apt-get install -y redis # here i customize githu SW by installing redis on ubuntu latest

      - name: Check Redis Connection
        run: redis-cli ping