name: 20 Basic Custom Action 2
run-name: ${{ github.actor }} Explaining Varaibles with Practical Example Run_Number ${{ github.run_number }}

on: workflow_dispatch

jobs:
  Hello-World-Job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
      - name: Print-Hello-World
        uses: ./.github/actions/print-hello-world/

     
