name: 21 Basic Github Client
run-name: ${{ github.actor }} Explaining Varaibles with Practical Example Run_Number ${{ github.run_number }}

on: workflow_dispatch

jobs:
  Open-New-Issue-Job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5.0.0
      - name: Print-Hello-World
        
        run: gh issue create --title "New Issue from Github Actions" --body "Nothing works"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

     
